version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app 
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cellartracker?schema=public

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cellartracker
    
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data: